compojure: /home/martin/opt/compojure
appengine_sdk_dir: /home/martin/opt/appengine-java-sdk-1.2.6
appengine_sdk_jar: /home/martin/opt/appengine-java-sdk-1.2.6/lib/user/appengine-api-1.0-sdk-1.2.6.jar
appengine_clj_jar: /home/martin/opt/appengine-clj/appengine-clj.jar
